-- 27 October 2022
-- Changes:
--  - Create account table
--  - Create group table
--  - Create account_in_group table
--  - Create group_invite table

-- Install UUID extension.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "account" (
    "id"    uuid         NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    -- See https://blog.greglow.com/2019/05/17/sql-column-length-storing-email-addresses-sqlserver-database/
    "email" varchar(320) NOT NULL UNIQUE,
    "name"  varchar(64)  NOT NULL,
    -- Hashes generated by bcrypt have a maximum length of 40 bytes.
    -- We set it to 64 just for safety, will set it to 40 once
    -- we're confident it works.
    "hash"  char(64)
);

CREATE TABLE IF NOT EXISTS "group" (
    "id"          uuid         NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
	"name"        varchar(32)  NOT NULL,
	"description" varchar(255)
);

-- Members of a group either have the admin role or no role (regular member). 
CREATE TYPE role_in_group AS ENUM ('admin');

-- Used to determin if a user is part of a group.
CREATE TABLE IF NOT EXISTS "account_in_group" (
    "account_id" uuid NOT NULL,
    "group_id"   uuid NOT NULL,
    "role"       role_in_group,

    CONSTRAINT "account_fk" FOREIGN KEY ("account_id") REFERENCES "account" ("id"),
    CONSTRAINT "group_fk" FOREIGN KEY ("group_id") REFERENCES "group" ("id"),
    CONSTRAINT "account_in_group_pk" PRIMARY KEY ("account_id", "group_id")
);

-- Stores who invited who to what group.
CREATE TABLE IF NOT EXISTS "group_invite" (
    "group_id"             uuid NOT NULL,
    "sender_account_id"    uuid NOT NULL,
    "recipient_account_id" uuid NOT NULL,

    CONSTRAINT "group_fk" FOREIGN KEY ("group_id") REFERENCES "group" ("id"),
    CONSTRAINT "sender_account_fk" FOREIGN KEY ("sender_account_id") REFERENCES "account" ("id"),
    CONSTRAINT "recipient_account_fk" FOREIGN KEY ("recipient_account_id") REFERENCES "account" ("id"),    
    CONSTRAINT "invite_pk" PRIMARY KEY ("sender_account_id", "recipient_account_id", "group_id")
)
